[package]
name = "state-wasm"
version = "0.1.0"
authors = ["j-arens <arens.joshua@sbcglobal.net>"]
edition = "2018"
build = "build.rs"

[lib]
crate-type = ["cdylib"]

[dependencies]
protobuf = "2.6.2"

[build_dependencies]
protobuf-codegen-pure = "2.6.2"
